---

#Configuring BGP on R3 and ISP (R4)

- hosts: R3
  gather_facts: false
  tasks:
    - name: BGP Configuration for R3
      cisco.ios.ios_bgp:
        config:
          bgp_as: 65000
          log_neighbor_changes: true
          neighbors:
          - neighbor: 192.168.77.1
            remote_as: 65100
          networks:
            - prefix: 192.168.77.0
              masklen: 24
          address_family:
            - afi: ipv4
              safi: unicast
              redistribute:
                - protocol: ospf
                  id: 1
        operation: merge

- hosts: R4
  gather_facts: false
  tasks:
    - name: BGP Configuration for R4
      cisco.ios.ios_bgp:
        config:
          bgp_as: 65100
          log_neighbor_changes: true
          neighbors:
          - neighbor: 192.168.77.2
            remote_as: 65000
          networks:
            - prefix: 192.168.99.0
              masklen: 24
          address_family:
            - afi: ipv4
              safi: unicast
        operation: merge